### ISSUE TITLE
Packages with a name <> CAS are not uploaded to AMS correctly

### ISSUE THREAD

**Issue by pianocktail** [SAP/cloud-authorization-buildpack#1]
The DCL file in the package <> DCL existst in the .jar file of the application but does not appear in the AMS 

If only one package <> CAS exists cf push fails with
> Downloaded build artifacts cache (1.1K)
> Error staging application: Staging error: staging failed
> FAILED 

When having 2 packages in the directory section  of the manifest the error during cf push is
>    tar: cas/\notherpackage: Cannot stat: No such file or directory

where "otherpackage" is the name of the second package.

**Comment by nenaraab** [comment]
you can test it by adding another package name into the `directories` property:
https://github.com/SAP/cloud-authorization-buildpack/blob/master/fixtures/node_with_opa/manifest.yml#L20

**Comment by d047491** [comment]
Fixed
