### ISSUE TITLE
credential_type vs credential-type

### ISSUE THREAD

**Issue by arapoport** [SAP/cloud-authorization-buildpack#38]
Buildpack prints a warning that has a typo in the advice:

`**WARNING** identity service binding does not contain client certificate. Please use binding parameter {"credential_type":"X509_GENERATED"}`

It should be `{"credential-type":"X509_GENERATED"}` (with an `-` instead of `_`).

See here:

https://github.com/SAP/cloud-authorization-buildpack/blob/5734f5694b51c66e46d2cec0cc506ebd679d7245/pkg/supply/services.go#L97

**Comment by jkbschmid** [comment]
Hi @arapoport ,
thanks for opening this ticket.
Fixed with e04bfb66341ee9d44abb857aef89d31cdecf5f1c
