### ISSUE TITLE
Link in About section is not shown correctly

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-authorization-buildpack#54]
Hello,

the about area contains a link to https://www.openpolicyagent.org/ but it's not shown correctly:

![Screenshot 2022-07-20 at 18 11 38](https://user-images.githubusercontent.com/2639535/180031051-4c5ff7a3-1049-46c4-a982-0da9fa388bb3.png)

Maybe the about section doesn't support Markdown formatting?

**Comment by f-blass** [comment]
Hi Gregor, 
thanks for the note. There does not seem to be a nice way to include links into the About area. For now I just removed the square brackets.
