### ISSUE TITLE
SAP CAP Application not able to deploy.

### ISSUE THREAD

**Issue by Jagan1002** [SAP/cloud-authorization-buildpack#85]
Hi Team,

Our SAP CAP springboot application not able to deploy after adding this buildpack.
Buildpack : "https://github.com/SAP/cloud-authorization-buildpack/releases/latest/download/opa_buildpack.zip".
Please check the attachment for this error:
[renegotiation-srv-green.log](https://github.com/SAP/cloud-authorization-buildpack/files/14596684/renegotiation-srv-green.log)

Regards,
Jaganathan Gu

**Comment by f-blass** [comment]
Solved internally.
